### ISSUE TITLE
Subdomain und E-Mail-Weiterleitung

### ISSUE THREAD

**Issue by binarious** [binarious/billing-service#1]
- [x] Subdomain (z. B. `payment.bin-co.de`)
- [x] Entsprechenden User und DB für die Subdomain
- [x] E-Mail-Weiterleitung von z. B. `payment@bin-co.de` an uns (würde ich als Absenderadresse für die E-Mails verwenden)

**Comment by aspann** [comment]
dev-env is reachable under: https://payment.complex-co.de/

i've mailed you the user, pass, etc.

**Comment by binarious** [comment]
:+1:
