### ISSUE TITLE
Annotations in (frontend-)controller

### ISSUE THREAD

**Issue by aspann** [binarious/billing-service#7]
Why not use annotations in the controllers to define the template?

```
   /**
     * @Route("/", name="homepage")
     * @Method("GET")
     */
    public function indexAction()
    {
        return $this->render('page/index.html.twig', []);
    }
```

IMHO, I think this should be better:

```
   /**
     * @Route("/", name="homepage")
     * @Method("GET")
     * @Template("AppBundle:page:index.html.twig")
     */
    public function indexAction()
    {
        return [];
    }
```

**Comment by binarious** [comment]
Using the template annotation is not the recommended option as the docs are
stating.

Armas Spann notifications@github.com schrieb am Di., 15. März 2016, 12:42:

**Comment by aspann** [comment]
Are you sure?
See: [Annotations (http://symfony.com/doc/)](http://symfony.com/doc/current/bundles/SensioFrameworkExtraBundle/annotations/view.html)

It gives us also the possibility to pass "vars" directly to the temlplate.

**Comment by binarious** [comment]
Yep: https://symfony.com/doc/current/best_practices/controllers.html#template-configuration and https://github.com/sensiolabs/SensioGeneratorBundle/pull/347
But I don't care much. If you like the annotation we can use that instead :).
